# Generated by Django 4.2.6 on 2023-10-31 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0005_alter_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='olxapp.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 7, 52, 31, 591784)),
        ),
    ]
