# Generated by Django 4.2.6 on 2023-10-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0006_alter_adds_title_alter_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
